# Generated by Django 5.2.5 on 2025-08-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetaxdata',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
