# Generated by Django 5.2.5 on 2025-08-29 07:46

import Tds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='Attire_Allowance_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Business_Communication_Allowance_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Children_Education_Allowance_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Conveyance_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Food_Coupons_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Furniture_Allowance_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='LeaveTA_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Medical_Reimbursement_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Petrol_Allowance_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section80cUtilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section80ccc_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section80cccd1b_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section80cccd2_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section80cccd_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section80d_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section80d_normal_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section80d_severe_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section80ddb_other_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section80ddb_seniorcitizen_Utilized_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80GGA_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80GGB_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80GGC_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80G_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80e_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80ee_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80eea_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80eeb_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80qqb_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80rrb_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80tta_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80ttb_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80u_Normal_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='Section_80u_severe_Doc',
            field=models.FileField(blank=True, null=True, upload_to=Tds.models.employee_directory_path),
        ),
    ]
