# Generated by Django 5.2.5 on 2025-09-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tds', '0002_alter_employeedocument_attire_allowance_utilized_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetaxdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
