# Generated by Django 5.2.5 on 2025-08-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductcertificate',
            name='template_choice',
            field=models.CharField(choices=[('template1', 'Template 1'), ('template2', 'Template 2'), ('template3', 'Template 3'), ('template4', 'Template 4')], default='template1', max_length=20),
        ),
    ]
