# Generated by Django 5.2.6 on 2025-09-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('enduser', 'End User (Student/Employee)'), ('principal', 'Principal'), ('hr', 'HR'), ('landlord', 'Landlord')], max_length=20),
        ),
    ]
