# Generated by Django 5.2.6 on 2025-09-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeejoiningpolicy',
            name='principal_signature',
        ),
        migrations.RemoveField(
            model_name='rentalagreement',
            name='principal_signature',
        ),
        migrations.AddField(
            model_name='employeejoiningpolicy',
            name='hr_signature',
            field=models.ImageField(blank=True, null=True, upload_to='hr_signatures/'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='landlord_signature',
            field=models.ImageField(blank=True, null=True, upload_to='landlord_signatures/'),
        ),
    ]
