# Generated by Django 5.2.5 on 2025-08-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
